version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - bodyclose
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/luckyrogue/lead-cat
