/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WebRouteImport } from './routes/_web'
import { Route as MiniappRouteImport } from './routes/_miniapp'
import { Route as MiniappIndexRouteImport } from './routes/_miniapp/index'
import { Route as WebDashboardRouteImport } from './routes/_web/dashboard'
import { Route as MiniappProfileRouteImport } from './routes/_miniapp/profile'
import { Route as MiniappMeetingsRouteImport } from './routes/_miniapp/meetings'
import { Route as MiniappCheckerRouteImport } from './routes/_miniapp/checker'
import { Route as MiniappProfileColleagueRouteImport } from './routes/_miniapp/profile.colleague'
import { Route as MiniappProfileAdminRouteImport } from './routes/_miniapp/profile.admin'
import { Route as MiniappMeetingsCreateRouteImport } from './routes/_miniapp/meetings.create'
import { Route as MiniappMeetingsMeetingIdRouteImport } from './routes/_miniapp/meetings.$meetingId'
import { Route as MiniappProfileAdminSetupRouteImport } from './routes/_miniapp/profile.admin.setup'
import { Route as MiniappMeetingsCreateEditIdRouteImport } from './routes/_miniapp/meetings.create.$editId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRoute = WebRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniappRoute = MiniappRouteImport.update({
  id: '/_miniapp',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniappIndexRoute = MiniappIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiniappRoute,
} as any)
const WebDashboardRoute = WebDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WebRoute,
} as any)
const MiniappProfileRoute = MiniappProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MiniappRoute,
} as any)
const MiniappMeetingsRoute = MiniappMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => MiniappRoute,
} as any)
const MiniappCheckerRoute = MiniappCheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => MiniappRoute,
} as any)
const MiniappProfileColleagueRoute = MiniappProfileColleagueRouteImport.update({
  id: '/colleague',
  path: '/colleague',
  getParentRoute: () => MiniappProfileRoute,
} as any)
const MiniappProfileAdminRoute = MiniappProfileAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => MiniappProfileRoute,
} as any)
const MiniappMeetingsCreateRoute = MiniappMeetingsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MiniappMeetingsRoute,
} as any)
const MiniappMeetingsMeetingIdRoute =
  MiniappMeetingsMeetingIdRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => MiniappMeetingsRoute,
  } as any)
const MiniappProfileAdminSetupRoute =
  MiniappProfileAdminSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => MiniappProfileAdminRoute,
  } as any)
const MiniappMeetingsCreateEditIdRoute =
  MiniappMeetingsCreateEditIdRouteImport.update({
    id: '/$editId',
    path: '/$editId',
    getParentRoute: () => MiniappMeetingsCreateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MiniappIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/checker': typeof MiniappCheckerRoute
  '/meetings': typeof MiniappMeetingsRouteWithChildren
  '/profile': typeof MiniappProfileRouteWithChildren
  '/dashboard': typeof WebDashboardRoute
  '/meetings/$meetingId': typeof MiniappMeetingsMeetingIdRoute
  '/meetings/create': typeof MiniappMeetingsCreateRouteWithChildren
  '/profile/admin': typeof MiniappProfileAdminRouteWithChildren
  '/profile/colleague': typeof MiniappProfileColleagueRoute
  '/meetings/create/$editId': typeof MiniappMeetingsCreateEditIdRoute
  '/profile/admin/setup': typeof MiniappProfileAdminSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof MiniappIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/checker': typeof MiniappCheckerRoute
  '/meetings': typeof MiniappMeetingsRouteWithChildren
  '/profile': typeof MiniappProfileRouteWithChildren
  '/dashboard': typeof WebDashboardRoute
  '/meetings/$meetingId': typeof MiniappMeetingsMeetingIdRoute
  '/meetings/create': typeof MiniappMeetingsCreateRouteWithChildren
  '/profile/admin': typeof MiniappProfileAdminRouteWithChildren
  '/profile/colleague': typeof MiniappProfileColleagueRoute
  '/meetings/create/$editId': typeof MiniappMeetingsCreateEditIdRoute
  '/profile/admin/setup': typeof MiniappProfileAdminSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_miniapp': typeof MiniappRouteWithChildren
  '/_web': typeof WebRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_miniapp/checker': typeof MiniappCheckerRoute
  '/_miniapp/meetings': typeof MiniappMeetingsRouteWithChildren
  '/_miniapp/profile': typeof MiniappProfileRouteWithChildren
  '/_web/dashboard': typeof WebDashboardRoute
  '/_miniapp/': typeof MiniappIndexRoute
  '/_miniapp/meetings/$meetingId': typeof MiniappMeetingsMeetingIdRoute
  '/_miniapp/meetings/create': typeof MiniappMeetingsCreateRouteWithChildren
  '/_miniapp/profile/admin': typeof MiniappProfileAdminRouteWithChildren
  '/_miniapp/profile/colleague': typeof MiniappProfileColleagueRoute
  '/_miniapp/meetings/create/$editId': typeof MiniappMeetingsCreateEditIdRoute
  '/_miniapp/profile/admin/setup': typeof MiniappProfileAdminSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/checker'
    | '/meetings'
    | '/profile'
    | '/dashboard'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/profile/admin'
    | '/profile/colleague'
    | '/meetings/create/$editId'
    | '/profile/admin/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/checker'
    | '/meetings'
    | '/profile'
    | '/dashboard'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/profile/admin'
    | '/profile/colleague'
    | '/meetings/create/$editId'
    | '/profile/admin/setup'
  id:
    | '__root__'
    | '/_miniapp'
    | '/_web'
    | '/login'
    | '/onboarding'
    | '/_miniapp/checker'
    | '/_miniapp/meetings'
    | '/_miniapp/profile'
    | '/_web/dashboard'
    | '/_miniapp/'
    | '/_miniapp/meetings/$meetingId'
    | '/_miniapp/meetings/create'
    | '/_miniapp/profile/admin'
    | '/_miniapp/profile/colleague'
    | '/_miniapp/meetings/create/$editId'
    | '/_miniapp/profile/admin/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MiniappRoute: typeof MiniappRouteWithChildren
  WebRoute: typeof WebRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_miniapp': {
      id: '/_miniapp'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MiniappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_miniapp/': {
      id: '/_miniapp/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MiniappIndexRouteImport
      parentRoute: typeof MiniappRoute
    }
    '/_web/dashboard': {
      id: '/_web/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WebDashboardRouteImport
      parentRoute: typeof WebRoute
    }
    '/_miniapp/profile': {
      id: '/_miniapp/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MiniappProfileRouteImport
      parentRoute: typeof MiniappRoute
    }
    '/_miniapp/meetings': {
      id: '/_miniapp/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MiniappMeetingsRouteImport
      parentRoute: typeof MiniappRoute
    }
    '/_miniapp/checker': {
      id: '/_miniapp/checker'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof MiniappCheckerRouteImport
      parentRoute: typeof MiniappRoute
    }
    '/_miniapp/profile/colleague': {
      id: '/_miniapp/profile/colleague'
      path: '/colleague'
      fullPath: '/profile/colleague'
      preLoaderRoute: typeof MiniappProfileColleagueRouteImport
      parentRoute: typeof MiniappProfileRoute
    }
    '/_miniapp/profile/admin': {
      id: '/_miniapp/profile/admin'
      path: '/admin'
      fullPath: '/profile/admin'
      preLoaderRoute: typeof MiniappProfileAdminRouteImport
      parentRoute: typeof MiniappProfileRoute
    }
    '/_miniapp/meetings/create': {
      id: '/_miniapp/meetings/create'
      path: '/create'
      fullPath: '/meetings/create'
      preLoaderRoute: typeof MiniappMeetingsCreateRouteImport
      parentRoute: typeof MiniappMeetingsRoute
    }
    '/_miniapp/meetings/$meetingId': {
      id: '/_miniapp/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof MiniappMeetingsMeetingIdRouteImport
      parentRoute: typeof MiniappMeetingsRoute
    }
    '/_miniapp/profile/admin/setup': {
      id: '/_miniapp/profile/admin/setup'
      path: '/setup'
      fullPath: '/profile/admin/setup'
      preLoaderRoute: typeof MiniappProfileAdminSetupRouteImport
      parentRoute: typeof MiniappProfileAdminRoute
    }
    '/_miniapp/meetings/create/$editId': {
      id: '/_miniapp/meetings/create/$editId'
      path: '/$editId'
      fullPath: '/meetings/create/$editId'
      preLoaderRoute: typeof MiniappMeetingsCreateEditIdRouteImport
      parentRoute: typeof MiniappMeetingsCreateRoute
    }
  }
}

interface MiniappMeetingsCreateRouteChildren {
  MiniappMeetingsCreateEditIdRoute: typeof MiniappMeetingsCreateEditIdRoute
}

const MiniappMeetingsCreateRouteChildren: MiniappMeetingsCreateRouteChildren = {
  MiniappMeetingsCreateEditIdRoute: MiniappMeetingsCreateEditIdRoute,
}

const MiniappMeetingsCreateRouteWithChildren =
  MiniappMeetingsCreateRoute._addFileChildren(
    MiniappMeetingsCreateRouteChildren,
  )

interface MiniappMeetingsRouteChildren {
  MiniappMeetingsMeetingIdRoute: typeof MiniappMeetingsMeetingIdRoute
  MiniappMeetingsCreateRoute: typeof MiniappMeetingsCreateRouteWithChildren
}

const MiniappMeetingsRouteChildren: MiniappMeetingsRouteChildren = {
  MiniappMeetingsMeetingIdRoute: MiniappMeetingsMeetingIdRoute,
  MiniappMeetingsCreateRoute: MiniappMeetingsCreateRouteWithChildren,
}

const MiniappMeetingsRouteWithChildren = MiniappMeetingsRoute._addFileChildren(
  MiniappMeetingsRouteChildren,
)

interface MiniappProfileAdminRouteChildren {
  MiniappProfileAdminSetupRoute: typeof MiniappProfileAdminSetupRoute
}

const MiniappProfileAdminRouteChildren: MiniappProfileAdminRouteChildren = {
  MiniappProfileAdminSetupRoute: MiniappProfileAdminSetupRoute,
}

const MiniappProfileAdminRouteWithChildren =
  MiniappProfileAdminRoute._addFileChildren(MiniappProfileAdminRouteChildren)

interface MiniappProfileRouteChildren {
  MiniappProfileAdminRoute: typeof MiniappProfileAdminRouteWithChildren
  MiniappProfileColleagueRoute: typeof MiniappProfileColleagueRoute
}

const MiniappProfileRouteChildren: MiniappProfileRouteChildren = {
  MiniappProfileAdminRoute: MiniappProfileAdminRouteWithChildren,
  MiniappProfileColleagueRoute: MiniappProfileColleagueRoute,
}

const MiniappProfileRouteWithChildren = MiniappProfileRoute._addFileChildren(
  MiniappProfileRouteChildren,
)

interface MiniappRouteChildren {
  MiniappCheckerRoute: typeof MiniappCheckerRoute
  MiniappMeetingsRoute: typeof MiniappMeetingsRouteWithChildren
  MiniappProfileRoute: typeof MiniappProfileRouteWithChildren
  MiniappIndexRoute: typeof MiniappIndexRoute
}

const MiniappRouteChildren: MiniappRouteChildren = {
  MiniappCheckerRoute: MiniappCheckerRoute,
  MiniappMeetingsRoute: MiniappMeetingsRouteWithChildren,
  MiniappProfileRoute: MiniappProfileRouteWithChildren,
  MiniappIndexRoute: MiniappIndexRoute,
}

const MiniappRouteWithChildren =
  MiniappRoute._addFileChildren(MiniappRouteChildren)

interface WebRouteChildren {
  WebDashboardRoute: typeof WebDashboardRoute
}

const WebRouteChildren: WebRouteChildren = {
  WebDashboardRoute: WebDashboardRoute,
}

const WebRouteWithChildren = WebRoute._addFileChildren(WebRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MiniappRoute: MiniappRouteWithChildren,
  WebRoute: WebRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
